version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/pat3"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "docker"
    directory: "/app-token"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
