name: Dependabot auto-merge using PAT
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && contains(github.event.pull_request.title, '/app-token') }}
    steps:
      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with: 
          app_id: 250668
          installation_id: 30381326
          private_key: ${{secrets.PRIVATE_KEY}}
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.4
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: echo metadata
        env:
          METADATA_OUTPUT: ${{ toJson(steps.metadata.outputs) }}
        run: echo "$METADATA_OUTPUT"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{contains(steps.metadata.outputs.dependency-names, 'bci/bci-base') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{steps.get_installation_token.outputs.token}}
